### ISSUE TITLE
Privacy policy update or GDPR compliance

### ISSUE THREAD

**Issue by D34THWINGS** [ritz078/transform#123]
Hi,

The Policy button on the top right corner says that data stays with the user but it's not. You're using Google Tag Manager and Google Analytics which retain user informations. I think you should either provide an accurate message regarding data usage or support the GDPR EU law program that requires you to put a banner displaying data usage on your website and provide a way to disable it.

Thanks !

**Comment by ritz078** [comment]
Sure. I am exploring this. I have got rid of tag manager and looking for an alternative solution of tracking anonymous page views.

**Comment by D34THWINGS** [comment]
Let me know if you need help on this or if you want to work on a PR! Thanks for the quick reply! Don't feel pressured by this though, I meant it as a general recommandation :)

**Comment by ritz078** [comment]
I will definitely need help on this. So the only data I need from the page are the basic ones like geography, page views, etc.

The first thing is making the messaging clear about what is being tracked.
Then create a flow to accept or deny that permission.

**Comment by D34THWINGS** [comment]
I think the message should something like:

> Transform uses cookies and collects data through Google Analytic to measure audience an dprovide a better service.

Maybe adding a link to some kind of privacy policy that you can copy/paste from another website, like most people do.

If you want true compliance, the only thing you need to do is to implement a banner/modal/popup that asks for user permission to collect data with a link to privacy policy and explanations about how to retrieve/delete personal data, etc. By default Google Analytics should not be activated, when user click accept you can then asynchronously mount Analytics into your website. Upon refusal, you hide the banner. The choice should be kept within localStorage or cookie to prevent from being asked each time the visit. Finally if you change: Privacy Policy/Data usage/Third parties using data or cookies; then you should ask again for user permission.
