### ISSUE TITLE
No fallback font for non-mac browsers

### ISSUE THREAD

**Issue by evmar** [ritz078/transform#129]
It appears to have hardcoded Mac-only fonts with no fallback.

**Comment by ritz078** [comment]
Can you check now and let me know if that's working ?

**Comment by evmar** [comment]
The editor widget is still using a sans-serif font, which I don't think is your intent.

**Comment by ritz078** [comment]
Can you suggest a code font that is pre-installed on your OS?

**Comment by evmar** [comment]
`monospace`
