### ISSUE TITLE
4xx error shows 5xx page. 

### ISSUE THREAD

**Issue by ritz078** [ritz078/transform#137]
If you open a wrong URL, 404 page should be shown instead of current 5xx page

**Comment by KonradLinkowski** [comment]
https://github.com/zeit/next.js/issues/8136

**Comment by ritz078** [comment]
I saw that. Thanks a lot for opening that issue.

I see the solution is mentioned there. would you like to open a PR?

**Comment by KonradLinkowski** [comment]
I'm not exactly sure how to use react component as functions as you do in those components, but I'll do my best

**Comment by ritz078** [comment]
Since we have to extend `App`, we will have to convert it into class first. So rather than using hooks we will have to use the general way of writing class components.

**Comment by ritz078** [comment]
@KonradLinkowski Let me know if you are working on this or not. :)

**Comment by KonradLinkowski** [comment]
I don't have much time to do that. You can take it if you want.

**Comment by ritz078** [comment]
No issues. I will take this :)
