### ISSUE TITLE
transform.tools as a vscode extension?

### ISSUE THREAD

**Issue by Shriram-Balaji** [ritz078/transform#151]
@ritz078 Thanks for this great project!

Currently I'm not able to find Vscode extensions that have a comprehensive list of transformations. Would making a vscode extension out of transform.tools be useful? Let me know your thoughts on this :smile:

**Comment by ritz078** [comment]
It will definitely be useful but currently I don't have the time to work on it.

**Comment by ritz078** [comment]
I don't think it's worth the effort to build this. Most of the transformations are done using independent packages those are already available on npm.
