### ISSUE TITLE
`null` is encoded as `string` in a couple of languages

### ISSUE THREAD

**Issue by zanza00** [ritz078/transform#163]
I found this bug while converting a JSON to `io-ts` that does also validation. Said validation will fail.

For example this JSON
```json
{
  "null": null,
  "string: ""
}
```
will be converted in 

```typescript
import * as t from "io-ts";

const RootInterface = t.type( {
  null: string,
  string: t.string,
});
```

Note that the validator is `string` and it also misses the `t` from the import. I think that value is a default one.

I tryed a couple more and found the following with the same `string`:
- sarcastic
- scala case class

**Comment by phdoerfler** [comment]
I suggest using `Option[String]` instead of `string` for the scala case class generator
