### ISSUE TITLE
New Feature: JSON to String with escape characters and vice versa

### ISSUE THREAD

**Issue by rmohta** [ritz078/transform#181]
If we add a new functionality to convert a well formed JSON to String with escape characters (like Java String). This will allow to call REST API that has a body parameter of type String and can process a JSON string. Think of like, additional options/settings.

**Example**
From `{"first_name": "First", "last_name": "Last"}`
To `"{\"first_name\":\"First\",\"last_name\":\"Last\"}"`

**Comment by ritz078** [comment]
Would you like to open a PR for this ?
