### ISSUE TITLE
JSON to MySQL schema crash when a property value is null

### ISSUE THREAD

**Issue by golopot** [ritz078/transform#218]
https://transform.tools/json-to-mysql

**Example:**

```js
{
  "foo": null
}
```

**Actual:**
A warning of
```
Cannot read property 'length' of null
```

**Expected:**
A proper warning that says fields cannot be null.

**Comment by golopot** [comment]
Upstream issue: https://github.com/nijikokun/generate-schema/issues/47

**Comment by 4n70w4** [comment]
Hi! Any news? The error is still there https://transform.tools/json-to-mysql.
