### ISSUE TITLE
Css to Js Object conversion :- Unitless Css Styles should not be converted to string

### ISSUE THREAD

**Issue by Rishabh-Rathod** [ritz078/transform#239]
same as the [issue](https://github.com/postcss/postcss-js/issues/48)
#### Expected Behaviour 
```
css -> z-index: 1;
js -> zIndex: 1,
```

#### Actual Behaviour :- 

```
css -> z-index: 1;
js -> zIndex: '1',
```

Css-In-Js libraries like JSS do not support string unitless values.

Solution: Upgrading postcss-js library to the latest version will resolve the issue as it was fixed by [this PR](https://github.com/postcss/postcss-js/pull/49)

Let me know if i need to send a PR to resolve it.

**Comment by ritz078** [comment]
Thanks for reporting the issue.

It will be great if you can open a PR.

**Comment by Rishabh-Rathod** [comment]
> Thanks for reporting the issue.
> 
> It will be great if you can open a PR.

sure i will send one.
