### ISSUE TITLE
JS to JSON to xxx

### ISSUE THREAD

**Issue by linonetwo** [ritz078/transform#244]
Can we have a combo system, that allows piping JS to JSON then to xxx?

So converting JS object to something else will be easier.

**Comment by linonetwo** [comment]
And currently , JS to JSON is hard to find.

**Comment by ritz078** [comment]
I am afraid this will complicate things and I don't see a lot of users wanting this. To keep the maintenance work minimal, I will try to focus on straightforward conversions like A to B.

So I am closing this for now.

**Comment by sibelius** [comment]
I think a JS -> JSON option would be cool

I'm using this https://www.convertonline.io/convert/js-to-json

**Comment by linonetwo** [comment]
we already have, it just hard to find because that category only.have one tool
