### ISSUE TITLE
Minor suggestions for JSX transform

### ISSUE THREAD

**Issue by gaearon** [ritz078/transform#252]
Hi folks, this looks like a great project. I'd like to link to it from the upcoming React docs rewrite.

It would be nice to fix a few small things though. In no particular order:

- By default, JSX has `;` at the end. This is rarely useful because you want to copy it as an expression. If you started writing `return ( )` and then paste the result in the middle, `;` will be a syntax error. This can really trip beginners. I suggest to remove `;` altogether.

- There is an option called "create class". It would be nice to change that to a function since there should be no good reason to convert some HTML to a class component anymore.

- By default, multiple elements get wrapped into a div. But React (and other libraries using JSX) has supported Fragments for a long time by now. Can we change this to generate `<> ... </>` instead?

Aside from these nits, it's really great.

**Comment by ritz078** [comment]
Thanks a lot for your suggestions Dan. These issues have been fixed now.
