### ISSUE TITLE
inline style react native to styled componentes

### ISSUE THREAD

**Issue by sibelius** [ritz078/transform#3]
```jsx
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
});
```

```jsx
const Container = styled.View`
   flex: 1;
   background-color: white;
`
```

**Comment by ritz078** [comment]
It won't be possible to detect if the element is `View`, `Text` etc.

**Comment by sibelius** [comment]
we can have some heuristics approaches (font-family needs a `Text`), or just convert everything to a View, and let the user finish the conversion

**Comment by ritz078** [comment]
I am not sure if a lot of people will need this feature. I will leave this open for feedback. If someone opens a PR, I will be happy to accept.
