### ISSUE TITLE
Convert HTML to Typescript

### ISSUE THREAD

**Issue by C-EO** [ritz078/transform#314]
Can you consider adding an HTML to Typescript converter?
It would be very useful.

**Comment by horizon0514** [comment]
how a html to typescript?  html is totally different from typescript.
what's your Usage Scenario

**Comment by C-EO** [comment]
I was creating a website purely out of Next JS and Typescript.
Now originally it was fully HTML and I wanted to convert it to Typescript.
And I found that the only way I could do that was by converting the HTML to JSX and then changing the JSX to TSX/TS.
But that was more work and an app like yours can really help developers to work around that more easily.

**Comment by ritz078** [comment]
HTML to TypeScript is a long road, and converting anything with no type information to something with types will always be buggy. So I won't be implementing this.
