### ISSUE TITLE
Support for dark mode

### ISSUE THREAD

**Issue by mikeytown19** [ritz078/transform#324]
I love this tool, but using it at night time is sure bright. 
Are there any plans to introduce a dark mode?

**Comment by ShivnathGupta** [comment]
@ritz078 can please use dark theme of  monaco editor `https://microsoft.github.io/monaco-editor/index.html`

**Comment by TheDesertKing** [comment]
Since this has yet to be implemented, I would suggest using a dark reader browser extension.

**Comment by ritz078** [comment]
We do have a temporary dark mode that will improve further in next version (WIP).

**Comment by tuyen-at-work** [comment]
After waiting for a proper dark mode, I create one for myself here:
https://transform.tuyen.blog/

It both has dark mode, as well as reponsive layout.
