### ISSUE TITLE
JSON Schema to Typescript

### ISSUE THREAD

**Issue by jamesbmorris92** [ritz078/transform#336]
When converting to typescript interfaces, JSON schema enumerations e.g.:
`"dataStoreType": {
	"description": "This should be 'internal' or 'external'.",
	"type": "string",
	"enum": ["external", "internal"]
},`
are converted to some sort of either syntax in typescript interfaces e.g.:
`dataStoreType: "external" | "internal"`

When parsing my JSON into my typescript interfaces it complains saying that:
` Type 'string' is not assignable to type '"external" | "internal"'.`

However this goes away when I set the interface property as type string or have the interface property reference a type e.g.:
`export type DataStoreType =
    | external
    | internal`

Is this an issue with how enumerations are treated in the conversion or is there something I can change in my tsConfig or something to support the typescript that get's generated?

**Comment by jamesbmorris92** [comment]
Apologies, i've just realised that the library you use for converting this is a third party library, I will move this issue there. Feel free to close

**Comment by ritz078** [comment]
I think it makes sense to move the discussion to the original package. Thank you. I am closing this.
