### ISSUE TITLE
changing transformer shouldn't change data the user inputs

### ISSUE THREAD

**Issue by DanielFGray** [ritz078/transform#52]
Needs some test that checks whether the json input is the default value or not before changing it

**Comment by morajabi** [comment]
I agree. If two transformers accept similar data types we shall not remove the user input.

**Comment by ritz078** [comment]
@morajabi @gyandeeps Are you guys interested in taking this up?

**Comment by KeshShan** [comment]
@ritz078 I would like to give it a try, since its still open

**Comment by ritz078** [comment]
@KeshShan sure
