### ISSUE TITLE
How to generate all Typescript classes for OpenApi schema? Definitions deeper in graph, related to "oneOf"?

### ISSUE THREAD

**Issue by chauey** [ritz078/transform#76]
I tried to paste in the OpenApi schema from https://github.com/Mermade/swagger2openapi/blob/master/schemas/openapi-3.0.json, but it does not generate classes for objects deeper in the graph. Is it related to "oneOf"? Advice? Thanks!

**Comment by chauey** [comment]
oh perhaps I need "unreachableDefinitions"

**Comment by ritz078** [comment]
Can you post an expected and actual result ?
