### ISSUE TITLE
ruby hash to JSON converter

### ISSUE THREAD

**Issue by ritz078** [ritz078/transform#81]

**Comment by p-racoon** [comment]
JSON and Ruby Hashes are pretty similar, but still, have their differences. One of them being that Ruby hashes allow Objects as keys, whereas JSON does not.
Example:-
```
Ruby:
{
    {'a'=>1} => 2
}
```
This is a valid Ruby hash, but JSON does not allow that.
hence, in this case, we can either call this as `invalid input for JSON conversion`, or we can do what  `to_JSON()` function does in ruby. 
So basically it would simply `Stringify` the object there is, and return
```
{
    "{\"a\"=>1}" : 2
}
``` 
(As shown in gif)
![RubyHashToJSON](https://user-images.githubusercontent.com/13845070/66861365-84076000-efac-11e9-95f3-63c65e13e622.gif)

Read more about to_json() [here] (https://apidock.com/rails/Hash/to_json) 
Try it yourself [here](https://www.tutorialspoint.com/execute_ruby_online.php)
_Remember to use `require 'json' `_

**Comment by p-racoon** [comment]
The JSON syntax or Definition in some sense can be found [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON#targetText=JavaScript%20and%20JSON%20differences,some%20JavaScript%20is%20not%20JSON.)

**Comment by p-racoon** [comment]
One more such issue is use and support of symbols in Ruby.
In Ruby, Symbols can be used as keys
```
{
    :a => 65   # a here is the symbol
}
```
This too is a valid Ruby hash, but JSON does not allow that.
Hence, in this case as well, we can either call this as invalid input for JSON conversion, or we can do what to_JSON() function does in ruby.
```
{
    "a" : 65
}
```
![RubyHashToJSONSymbolsAsKey](https://user-images.githubusercontent.com/13845070/66862565-c3cf4700-efae-11e9-8c15-0428457b44f0.gif)
Ref: https://docs.ruby-lang.org/en/2.3.0/Hash.html
Try it [here] (https://www.tutorialspoint.com/execute_ruby_online.php)

**Comment by ritz078** [comment]
We should do what `to_JSON()` does in all cases.

**Comment by p-racoon** [comment]
I found [this library named Opal](https://opalrb.com/#targetText=Opal%20is%20a%20Ruby%20to,and%20small%20in%20its%20footprint.) should we use this or stick to building a compiler?

**Comment by ritz078** [comment]
you can use 3rd party libraries if they work
