### ISSUE TITLE
JSON to React PropTypes.func

### ISSUE THREAD

**Issue by jake-nz** [ritz078/transform#83]
Thanks for the handy tool!
It looks like [transform-it/babel-plugin-json-to-proptypes supports](https://github.com/transform-it/babel-plugin-json-to-proptypes/blob/master/src/index.js#L59)  `()=>{}` →`PropTypes.func` and `function(){}` →`PropTypes.func` but it's not working on https://transform.now.sh/. 
Is this something that can be added?

**Comment by ritz078** [comment]
can be done. instead of JSON, I will have to add support for JS object. I will do it ASAP.
