### ISSUE TITLE
Nondeterministic missing fields in JSON Schema to Rust Serde

### ISSUE THREAD

**Issue by dtolnay** [ritz078/transform#89]
In this sample input https://transform.now.sh/json-schema-to-rust-serde/ the resulting struct needs to have 6 fields: firstName, lastName, age, height, favoriteFoods, likesDogs. Usually the output is correct but if you toggling the Snake Case checkbox a dozen times or so, occasionally you will see it output a struct that only has 5 fields with favoriteFoods missing.

**Comment by ritz078** [comment]
I might have handled state changes wrongly. I will check. Thanks for reporting :)
