### ISSUE TITLE
Elasticsearch mapping

### ISSUE THREAD

**Issue by RWOverdijk** [ritz078/transform#98]
First off thank you for building this. I use it daily for typescript, mst, react, sql... It's a huge time saver.

Now! It would be awesome if it also supported elasticsearch mappings, which I think can be done seeing as how they're quite simple _generally_.

**Comment by ritz078** [comment]
It's more like converting a JSON to JSON schema. That's not going to be straightforward. I will see what's possible. Meanwhile, PR is welcome.

**Comment by RWOverdijk** [comment]
I don't know how the tool works but I assume that at the center of it there's something that extracts info from the json, and that the generators all interpret that differently, no? So wouldn't this be a matter of writing that back into json?

This is just me being curious by the way 😄

**Comment by ritz078** [comment]
You can get an idea about that [here](https://github.com/transform-it/transform-json-types)
